name: Windows Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install CMake
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Install Conan
      run: pip install conan

    - name: Configure Conan
      run: conan profile detect --force

    - name: Build Standard Version
      run: |
        conan install . --output-folder=build --build=missing -s compiler.cppstd=17
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Build Qt Version
      run: |
        conan export . --name=gbcemulator --version=0.1.5
        cd qt_wrap
        conan install . --output-folder=build --build=missing -s compiler.cppstd=17
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
