name: Windows Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install CMake
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Install Conan 1.x
      run: pip install "conan<2.0"

    - name: Configure Conan
      run: |
        conan profile new default --detect --force
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

    - name: Build Standard Version
      run: |
        conan install . -if=build --build=outdated -s compiler.cppstd=17
        copy D:\a\GBCEmulator\GBCEmulator\build\build\conaninfo.txt D:\a\GBCEmulator\GBCEmulator\build\conaninfo.txt
        copy D:\a\GBCEmulator\GBCEmulator\build\build\conanbuildinfo.txt D:\a\GBCEmulator\GBCEmulator\build\conanbuildinfo.txt
        xcopy "D:\a\GBCEmulator\GBCEmulator\build\build\generators" "D:\a\GBCEmulator\GBCEmulator\build\generators" /s /e /i /y
        conan build . -bf=build

    - name: Build Qt Version
      run: |
        conan export conanfile.py josh/testing
        cd qt_wrap
        conan install . -if=build --build=outdated -s compiler.cppstd=17
        conan build . -bf=build
